using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using WorkflowCore.AI.AzureFoundry.Models;

namespace WorkflowCore.AI.AzureFoundry.Interface
{
    /// <summary>
    /// Service for chat completion operations
    /// </summary>
    public interface IChatCompletionService
    {
        /// <summary>
        /// Complete a chat conversation
        /// </summary>
        /// <param name="messages">Conversation messages</param>
        /// <param name="model">Model to use (null for default)</param>
        /// <param name="temperature">Temperature (null for default)</param>
        /// <param name="maxTokens">Max tokens (null for default)</param>
        /// <param name="tools">Available tools for the LLM to call</param>
        /// <param name="cancellationToken">Cancellation token</param>
        Task<ChatCompletionResponse> CompleteAsync(
            IEnumerable<ConversationMessage> messages,
            string model = null,
            float? temperature = null,
            int? maxTokens = null,
            IEnumerable<ToolDefinition> tools = null,
            CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Response from a chat completion request
    /// </summary>
    public class ChatCompletionResponse
    {
        /// <summary>
        /// The message generated by the model
        /// </summary>
        public ConversationMessage Message { get; set; }

        /// <summary>
        /// Reason the completion finished (stop, tool_calls, length, content_filter)
        /// </summary>
        public string FinishReason { get; set; }

        /// <summary>
        /// Number of tokens in the prompt
        /// </summary>
        public int PromptTokens { get; set; }

        /// <summary>
        /// Number of tokens in the completion
        /// </summary>
        public int CompletionTokens { get; set; }

        /// <summary>
        /// Total tokens used
        /// </summary>
        public int TotalTokens => PromptTokens + CompletionTokens;

        /// <summary>
        /// Model used for the completion
        /// </summary>
        public string Model { get; set; }
    }
}
