// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WorkflowCore.Persistence.Oracle;

#nullable disable

namespace WorkflowCore.Persistence.Oracle.Migrations
{
    [DbContext(typeof(OracleContext))]
    partial class OracleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
#if NET6_0  
                .HasAnnotation("ProductVersion", "7.0.0")
#elif NET8_0
                .HasAnnotation("ProductVersion", "9.0.9")
#else
                .HasAnnotation("ProductVersion", "9.0.9")
#endif
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedEvent", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<string>("EventData")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventTime");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("EventName", "EventKey");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionError", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<DateTime>("ErrorTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ExecutionPointerId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Message")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("PersistenceId");

                    b.ToTable("ExecutionError", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Children")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ContextItem")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EventData")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EventKey")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<bool>("EventPublished")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Outcome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PersistenceData")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PredecessorId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Scope")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("SleepUntil")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("StepId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StepName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("ExecutionPointer", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExtensionAttribute", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("ExecutionPointerId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("ExecutionPointerId");

                    b.ToTable("ExtensionAttribute", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedScheduledCommand", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<string>("CommandName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Data")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<long>("ExecuteTime")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("ExecuteTime");

                    b.HasIndex("CommandName", "Data")
                        .IsUnique()
                        .HasFilter("\"CommandName\" IS NOT NULL AND \"Data\" IS NOT NULL");

                    b.ToTable("ScheduledCommand", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedSubscription", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<string>("EventKey")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("ExecutionPointerId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("ExternalToken")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("ExternalTokenExpiry")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ExternalWorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("StepId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("SubscribeAsOf")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("SubscriptionData")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("RAW(16)");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("EventKey");

                    b.HasIndex("EventName");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedWorkflow", b =>
                {
                    b.Property<long>("PersistenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersistenceId"), 1L, 1);

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Data")
                        .HasColumnType("CLOB");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<Guid>("InstanceId")
                        .HasMaxLength(200)
                        .HasColumnType("RAW(16)");

                    b.Property<long?>("NextExecution")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Version")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("PersistenceId");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.HasIndex("NextExecution");

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", b =>
                {
                    b.HasOne("WorkflowCore.Persistence.EntityFramework.Models.PersistedWorkflow", "Workflow")
                        .WithMany("ExecutionPointers")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExtensionAttribute", b =>
                {
                    b.HasOne("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", "ExecutionPointer")
                        .WithMany("ExtensionAttributes")
                        .HasForeignKey("ExecutionPointerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPointer");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedExecutionPointer", b =>
                {
                    b.Navigation("ExtensionAttributes");
                });

            modelBuilder.Entity("WorkflowCore.Persistence.EntityFramework.Models.PersistedWorkflow", b =>
                {
                    b.Navigation("ExecutionPointers");
                });
#pragma warning restore 612, 618
        }
    }
}
